version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=smsub_user
      - MARIADB_DATABASE=smsub
    ports:
      - "${DB_PORT:-17306}:3306"
  smsub:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8097:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=smsub_user
      - DB_DATABASE=smsub
    volumes:
      - './src:/app'
    depends_on:
      - mariadb
